services:
  db:
    image: legend0fhell/db:latest
    environment:
      - POSTGRES_USER=isle_user
      - POSTGRES_PASSWORD=isle_password
      - POSTGRES_DB=asl_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - isle-network
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  api:
    image: legend0fhell/api:latest
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - isle-network
    restart: unless-stopped

  ml:
    image: legend0fhell/ml:latest
    ports:
      - "15100:15100"
    networks:
      - isle-network
    restart: unless-stopped

  site:
    image: legend0fhell/site:latest
    environment:
      - NEXT_PUBLIC_API_URL=http://nginx/api
      - NEXT_PUBLIC_WEBSOCKET_URL=http://nginx
      - NODE_ENV=production
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - isle-network

  nginx:
    image: legend0fhell/nginx:latest
    ports:
      - "80:80"
    depends_on:
      api:
        condition: service_started
      site:
        condition: service_started
      ml:
        condition: service_started
      db:
        condition: service_healthy
    networks:
      - isle-network
    restart: unless-stopped

volumes:
  pgdata:


networks:
  isle-network:
    driver: bridge

